# Balanced synthetic data generation parameters

# Price dynamics
mu: 0.0                    # Drift (annualized)
sigma: 0.1                 # Lower volatility (annualized)
initial_price: 100.0      # Starting midprice

# Market microstructure
spread_mean: 0.002         # Smaller spread (0.2% instead of 1%)
spread_vol: 0.001          # Lower spread volatility
lambda_orders: 5.0         # Lower order frequency

# Episode parameters
episode_length: 1000       # Number of steps per episode
dt: 0.001                  # Time step (1ms)

# Domain randomization (per episode)
volatility_range: [0.08, 0.12]    # Ïƒ range for randomization
spread_range: [0.001, 0.003]       # Spread range for randomization
latency_range: [1, 3]              # Latency range (steps)
fee_range: [0.00005, 0.0001]        # Lower fee range

# Risk controls
max_inventory: 100.0           # Lower max inventory
max_loss_per_episode: 100.0    # Lower max loss
kill_switch_threshold: -200.0  # Lower kill switch

# Reward parameters
lambda_inventory: 0.001         # Much lower inventory penalty
transaction_fee: 0.00005        # Lower transaction fee

# Training parameters (for quick testing)
total_timesteps: 50000          # Reduced for quick testing
eval_freq: 5000                 # Evaluate every 5k steps
save_freq: 10000                # Save every 10k steps
