# Synthetic data generation parameters

# Price dynamics
mu: 0.0                    # Drift (annualized)
sigma: 0.2                 # Volatility (annualized)
initial_price: 100.0      # Starting midprice

# Market microstructure
spread_mean: 0.01          # Average spread (as fraction of price)
spread_vol: 0.005          # Spread volatility
lambda_orders: 10.0        # Poisson rate for market orders (per step)

# Episode parameters
episode_length: 1000       # Number of steps per episode
dt: 0.001                  # Time step (1ms)

# Domain randomization (per episode)
volatility_range: [0.15, 0.25]    # Ïƒ range for randomization
spread_range: [0.005, 0.015]       # Spread range for randomization
latency_range: [1, 5]              # Latency range (steps)
fee_range: [0.0001, 0.0005]        # Fee range (as fraction of notional)
