# Tuned Environment Configuration
# Designed to make random strategies less profitable and reward smart strategies

# Market dynamics - Much more challenging
mu: 0.0                    # No drift (random walk)
sigma: 0.5                 # Much higher volatility
initial_price: 100.0
spread_mean: 0.05          # Much wider spreads
spread_vol: 0.02           # High spread volatility
lambda_orders: 2.0         # Much lower order frequency
episode_length: 1000
dt: 0.001

# Domain randomization - Very challenging
volatility_range: [0.4, 0.6]       # Very high volatility range
spread_range: [0.03, 0.07]         # Very wide spread range

# Fill model - Much more realistic
fill_alpha: 0.5            # Much lower base fill probability
fill_beta: 5.0             # Much faster decay

# Risk controls - Stricter
max_inventory: 500.0       # Lower max inventory (was 1000.0)
max_loss_per_episode: 500.0 # Lower max loss (was 1000.0)
kill_switch_threshold: -2000.0 # Earlier kill switch (was -5000.0)

# Reward parameters - More penalizing
lambda_inventory: 0.02    # Higher inventory penalty (was 0.01)
transaction_fee: 0.0002   # Higher transaction fees (was 0.0001)

# Environment parameters
episode_length: 1000
latency: 1
max_inventory: 500.0
max_loss_per_episode: 500.0

# Action space parameters
action_offsets: [0.0, 0.5, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5]  # More granular
action_sizes: [10.0, 20.0, 30.0, 40.0, 50.0]  # Smaller sizes

# Observation space
observation_features: 5
normalize_observations: true
